name: Build and Deploy

on:
  push:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          make lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: vars
        run: |
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          # Set default branch name for PRs, as we still want to test build an image on PRs
          # but we have no branch to set a tag for.
          branch="test"
          if [[ "$GITHUB_REF" == "refs/heads/"* ]]; then
            branch="${GITHUB_REF#refs/heads/}"
          fi
          echo "branch=${branch}" >> $GITHUB_ENV
      - run: |
          make build
          docker build -t ${{ secrets.ADHP_DOCKER_USERNAME }}/zan-ids:${{ env.branch }} -t ${{ secrets.ADHP_DOCKER_USERNAME }}/zan-ids:${{ env.branch }}-${{ env.sha_short }} .
          docker push ${{ secrets.ADHP_DOCKER_USERNAME }}/zan-ids:${{ env.branch }}
          docker push ${{ secrets.ADHP_DOCKER_USERNAME }}/zan-ids:${{ env.branch }}-${{ env.sha_short }}